<a href="https://colab.research.google.com/github/Eleemon98/Colaboratory/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# 넘파이 모듈 불러오기, as는 별칭 붙인 것(넘파이 별칭은 np로 정해져 있음)

In [ ]:
num = [1,2,3,4,5,6,7,8,9]
result = num + [3]
result

[1, 2, 3, 4, 5, 6, 7, 8, 9, 3]

In [ ]:
num + 3
# 형태가 달라서 프로그래밍 언어에서 안 되는 게 정상

TypeError: can only concatenate list (not "int") to list

In [ ]:
arr = np.array(num)
arr + np.array([3])
arr + 3

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
new_num = []
for i in num:
  new_num.append(i+3)
new_num

[4, 5, 6, 7, 8, 9, 10, 11, 12]

In [ ]:
# 리스트 컴플레이션
new_num = [i+3 for i in num]
new_num

[4, 5, 6, 7, 8, 9, 10, 11, 12]

In [ ]:
# List의 반복문 수행 시간 측정
import time # 시간 재는 기능

num = range(10000)
result = []
start = time.time()
for i in num:
  i += 3
  result.append(i)
end = time.time()
sec = (end - start) * 1000
print(f"{sec:.4f} sec")
print(result[-5:])

1.9572 sec
[9998, 9999, 10000, 10001, 10002]


In [ ]:
# numpy의 array 수행 시간 측정
import time
import numpy as np

num = np.arange(10000)
start = time.time()
result = num + 3
end = time.time()
sec = (end - start) * 1000
print(f"{sec: .5f} sec")
print(result[-5:])

 0.37026 sec
[ 9998  9999 10000 10001 10002]


In [ ]:
text = ['I','Love','Python']
text2 = ['(나)','(좋아해)','(파이썬)']

result = text + text2
result

['I', 'Love', 'Python', '(나)', '(좋아해)', '(파이썬)']

In [ ]:
import numpy as np

arr_str = np.array(['I','Love','Python'],dtype=object)
arr_str2 = np.array(['(나)','(좋아해)','(파이썬)'])

result = arr_str + arr_str2
result

array(['I(나)', 'Love(좋아해)', 'Python(파이썬)'], dtype=object)

In [ ]:
import numpy as np

arr = np.array([[1,2]])

print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
import numpy as np

arr = np.array([[0,0,0],
								[1,1,1]])

In [ ]:
arr

array([[0, 0, 0],
       [1, 1, 1]])

In [ ]:
arr.shape

(2, 3)

In [ ]:
arr.ndim

2

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
import numpy as np

arr = np.array([1,2,3])
# arr2 = np.array([1,2,3], float)
# print(arr.dtype, arr2.dtype)
# arr.astype(float)
arr.dtype

dtype('int64')

In [ ]:
arr = np.array([1,2,3], float)
arr.dtype

dtype('float64')

In [ ]:
arr = np.array([1,2,3], object)
arr.dtype

dtype('O')

In [ ]:
arr.astype(str) #변경은 시켜주지만 적용은 안 됨

array(['1', '2', '3'], dtype='<U1')

In [ ]:
arr.dtype

dtype('O')

In [ ]:
arr = arr.astype(str) # 적용은 직접 시켜줘야함

In [ ]:
arr.dtype

dtype('<U1')

In [ ]:
zer = np.zeros(2)
zer2 = np.zeros((3,2))
zer3 = np.zeros((2,3,2))
print(zer)
print('--------------------')
print(zer2)
print('--------------------')
print(zer3)

[0. 0.]
--------------------
[[0. 0.]
 [0. 0.]
 [0. 0.]]
--------------------
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [ ]:
lin = np.arange(2,8)
lin2 = np.linspace(3,7,10)

print(lin)
print('--------------------')
print(lin2)

[2 3 4 5 6 7]
--------------------
[3.         3.44444444 3.88888889 4.33333333 4.77777778 5.22222222
 5.66666667 6.11111111 6.55555556 7.        ]


In [ ]:
iden = np.identity(3)
iden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
eye = np.eye(3)
eye2 = np.eye(3,k=1)
eye3 = np.eye(3,5)

print(eye)
print('--------------------')
print(eye2)
print('--------------------')
print(eye3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
--------------------
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
--------------------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [ ]:
li = [[1,2,3], [4,5,6]]

In [ ]:
li[0][1:]

[2, 3]

In [ ]:
arr = np.array(li)

In [ ]:
arr[0][1:]

array([2, 3])

In [ ]:
arr[0,1:]

array([2, 3])

In [ ]:
li = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [ ]:
result = []
for i in li:
  if i % 2 == 0:
    result.append(i)
print(result)

[2, 4, 6, 8, 10, 12]


In [ ]:
li2 = [[2, 1, 3, 4], [7, 6, 8, 5], [9, 10, 11, 12]]

In [ ]:
result = []
for i in li2:
  for j in i:
    if j % 2 == 0:
      result.append(j)
result

[2, 4, 6, 8, 10, 12]

In [ ]:
arr = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
arr = np.array(li)

In [ ]:
arr[arr%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
arr2 = np.array(li2)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr2[arr2%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
arr2.reshape((12,))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
arr2.shape

(3, 4)

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
arr.resize(2,3,2)

In [ ]:
arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [ ]:
arr2.resize(5,5, refcheck=False) # refcheck는 다른 코드와의 관계를 끊는 명령어

In [ ]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [ ]:
arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [ ]:
arr.reshape(3,2,-1) # 마지막 숫자를 -1로 넣으면 알아서 계산해서 만들어줌

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
arr = np.array([[1,2],[3,4],[5,6]])

In [ ]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
arr.shape

(3, 2)

In [ ]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr.T

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
zr= np.zeros((2,3,4,5))

In [ ]:
zr.shape

(2, 3, 4, 5)

In [ ]:
zr.T

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [

In [ ]:
zr.T.shape # 전치행렬

(5, 4, 3, 2)

In [ ]:
zr.transpose(3, 0, 2, 1).shape # 원하는 대로 축을 변경 가능

(5, 2, 4, 3)

In [ ]:
zr.swapaxes(0,3).shape # 원하는 축 2개만 서로 변경할 때 사용

(5, 3, 4, 2)

In [ ]:
import numpy as np

a = np.array([[1,2],[3,4]])

b = np.array([[5,6]])

In [ ]:
a + b

array([[ 6,  8],
       [ 8, 10]])

In [ ]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
c = np.array([[5], [6]])

In [ ]:
np.concatenate((a,c), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
a*b

array([[ 5, 12],
       [15, 24]])

In [ ]:
s = np.array([[1,2],[3,4],[5,6]])

In [ ]:
s.sum()

21

In [ ]:
s.sum(axis=0)

array([ 9, 12])

In [ ]:
s.sum(axis=1)

array([ 3,  7, 11])

In [ ]:
import numpy as np

arr = np.array(np.arange(1,11))

print(arr.sum())

print(arr.cumsum())


55
[ 1  3  6 10 15 21 28 36 45 55]


In [ ]:
arr = np.array(np.arange(1,11)).reshape(2,5)
print(arr)
print('---------------')
print(arr.sum(axis=0))
print(arr.sum(axis=1))
print('---------------')
print(arr.cumsum(axis=0))
print(arr.cumsum(axis=1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
---------------
[ 7  9 11 13 15]
[15 40]
---------------
[[ 1  2  3  4  5]
 [ 7  9 11 13 15]]
[[ 1  3  6 10 15]
 [ 6 13 21 30 40]]


In [ ]:
arr = np.array(np.arange(1,11)).reshape(2,5)
print(arr)
print('---------------')
print(arr.min(axis=0))
print(arr.min(axis=1))
print('---------------')
print(arr.max(axis=0))
print(arr.max(axis=1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
---------------
[1 2 3 4 5]
[1 6]
---------------
[ 6  7  8  9 10]
[ 5 10]


In [ ]:
arr = np.array(np.arange(1,17)).reshape(2,4,2)
print(arr)
print('---------------')
print(arr.sum(axis=0))
print(arr.sum(axis=1))
print(arr.sum(axis=2))

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]
---------------
[[10 12]
 [14 16]
 [18 20]
 [22 24]]
[[16 20]
 [48 52]]
[[ 3  7 11 15]
 [19 23 27 31]]


In [ ]:
import numpy as np

arr = np.array(np.random.randint(1,10,5))
arr

# print(arr.min())

# print(arr.max())

array([2, 5, 6, 4, 9])

In [ ]:
arr = np.random.randint(1,10,6)
arr

array([3, 3, 2, 3, 7, 9])

In [ ]:
np.unique(arr)

array([2, 3, 7, 9])

In [ ]:
np.unique([1,1,2,3,4,6,2], return_counts=True)

(array([1, 2, 3, 4, 6]), array([2, 2, 1, 1, 1]))

In [ ]:
arr = np.array([1,5,2,3,7,8,9,4]).reshape(2,4)
print(arr)

[[1 5 2 3]
 [7 8 9 4]]


In [ ]:
arr_c = np.sort(arr, axis=0)
print(arr_c)

[[1 5 2 3]
 [7 8 9 4]]


In [ ]:
arr_r = np.sort(arr, axis=1)
print(arr_r)

[[1 2 3 5]
 [4 7 8 9]]


In [ ]:
np.random.choice(np.arange(1, 11), size=5, replace=False)

array([ 4, 10,  9,  1,  6])